# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml
name: Test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"
    pull_request:
    push:

jobs:
    test:
        if: contains(github.event.commits[0].message, '[ci]') == false
        name: Unit Tests
        runs-on: windows-latest
        timeout-minutes: 10
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Install Roblox Studio
              uses: OrbitalOwen/roblox-win-installer-action@1.1
              with:
                  cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_902AE930D151814C00F4E7E17A1721DF12F917586DFAE44C473F5EB21F9099CA676D55F646DE2E127D796ED2DD2315D3D1741169A8996673E64BC79F913E0E24AC61E6344B50B6CBE8D25283BBAA0C092F486427144FB431B8DB2988CAE05D74330C4BFB100D33F489672DBCDD77B968E030120662D18BA74865187F2AB33A45E49EF80481EADFF3095DCB89F3AE7888AB4A49C5E60C76B2CA7515F91419CC689BE5DACD552F9B26D500CB8A817011D3245EC1400D881E69A7F3377A1B28978FA9272C152986CAD12CA121B3079750E081AB936031AA04883C2519C740BD9E64ADA64F3FAAD0D6D683FCFF3AB6DFA484EC3CF9ED10E260CA4BAA9C35146C3797F72B211982C714F05C75D241EBC42E775C56B7359E34F988F7AF34227D63CB7778C51AA72D88F14174FC255F17BACC25A77D55F7A443C868AEA4B569B1F735BEB54B9FFA' }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Foreman
              uses: rojo-rbx/setup-foreman@v1.0.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4

            - name: Compile and run tests
              run: npm test

            # - name: Report Coverage
            #   continue-on-error: true
            #   uses: coverallsapp/github-action@v1.1.2
            #   with:
            #       github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Generated Files
              if: github.repository == 'Ukendio/Game' &&
                  github.ref == 'refs/heads/master'
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "noreply@github.com"
                  git add -A
                  if (git diff-index --quiet HEAD --) {}
                  else {
                    echo "Generated files changed!"
                    git commit -m "${{github.event.commits[0].author.name}}: ${{github.event.commits[0].message}} [ci]"
                    git push https://Ukendio:${{ secrets.github_token }}@github.com/Ukendio/Game.git HEAD:master
                  }
